config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users do
    resources :trails
  end

  resources :rides
  
  resources :trails
  root to: "trails#welcome"
  get '/signup', to: "users#new"
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ride.rb
class Ride < ApplicationRecord
  belongs_to :user
  belongs_to :trail
end

app/models/route.rb
class Route < ApplicationRecord
  has_many :rides
  has_many :users, through: :rides
end

app/models/trail.rb
class Trail < ApplicationRecord
  has_many :rides
  has_many :users, through: :rides
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  validates :username, presence: true
  validates :password, length: { minimum: 8 }, on: :create

  has_many :rides
  has_many :trails, through: :rides
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  
  def index
    @rides = Ride.all
  end

  def new
    @ride = Ride.new
  end

  def create
    @ride = Ride.create(ride_params)
  end

  private

  def ride_params
    params.require(:ride).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    @user = User.where('username LIKE ?', "%#{params[:username]}%").first
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      
      redirect_to user_path(@user)
    else
      redirect_to login_path
    end
  end 

  def destroy
    session.delete :user_id

    redirect_to trails_path
  end
end

app/controllers/trails_controller.rb
class TrailsController < ApplicationController

  def welcome

  end

  def index
    if params[:user_id]
      @trails = User.find(params[:user_id]).trails
    else
      @trails = Trail.all
    end
  end

  def new
    @trail = Trail.new
  end

  def show
    @trail = Trail.find(params[:id])
  end

  def create
    @trail = Trail.create(trail_params)
    if @trail.save
      if @current_user
        @current_user.trails << @trail
        @current_user.save
      end
      redirect_to trail_path(@trail)
    else
      redirect_to new_trail_path
    end
  end

  def edit
    @trail = Trail.find(params[:id])
  end

  def update
    @trail = Trail.update(trail_params)
    if @trail
      redirect_to trail_path(@trail)
    else
      redirect_to new_trail_path
    end
  end

  def destroy
    @trail = Trail.find(params[:id]).destroy

    redirect_to trails_path
  end

  private

  def trail_params
    params.require(:trail).permit(:name, :length)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      
      redirect_to user_path(@user)
    else
      render "new"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.update(user_params)
    if @user
      redirect_to user_path(@user)
    else
      redirect_to trails_path
    end
  end

  def destroy
    @user = User.find(params[:id]).destroy

    redirect_to trails_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :first_name, :last_name, :password, :birthdate)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/trails_helper.rb
module TrailsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
  end
end

app/views/application/_navigation.html.erb
<% if !session[:user_id] %>
  <p class="nav_link"><%= link_to "Sign Up!", new_user_path %></p>
  <p class="nav_link"><%= link_to "Log In", login_path %></p>
<% else %>
  <p class="nav_link"><%= link_to "Log Out", logout_path, method: :delete %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trailsetmc</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'navigation' %>
    <br><br>
    <%= yield %>
  </body>
</html>

app/views/rides/index.html.erb
<% @rides.each do |ride| %>
  <%= ride.name %>
  <%= ride.length %>
<% end %>

app/views/routes/_form.html.erb
<%= form_for @route do |f| %>
  <%= f.label "Name:" %>
  <br>
  <%= f.text_field :name %>
  <br>
  <%= f.label "Length:" %>
  <br>
  <%= f.number_field :length, min: 0, max: 50 %>
  <br>
  <br>
  <%= f.submit %>
<% end %>

app/views/trails/_form.html.erb
<%= form_for @trail do |f| %>
  <%= f.label "Name:" %>
  <br>
  <%= f.text_field :name %>
  <br>
  <%= f.label "Length:" %>
  <br>
  <%= f.number_field :length, min: 0, max: 50, step: 0.1 %>
  <br>
  <br>
  <%= f.submit %>
<% end %>

app/views/trails/edit.html.erb
<%= render 'form' %>

app/views/trails/index.html.erb
<% @trails.each do |trail| %>
  <strong>Name: </strong><%= trail.name %>
  <br>
  <strong>Length: </strong><%= trail.length %> miles
  <br>
  <strong>Created by: </strong>
  <% if trail.users.blank? %>
    Anonymous
  <% else %>
    <%= link_to trail.users.first.username, user_path(trail.users.first) %>
  <% end %>
  <br>
  <%= link_to "View #{trail.name}", trail_path(trail) %>
  <br>
  <br>
<% end %>

app/views/trails/new.html.erb
<%= render 'form' %>

app/views/trails/show.html.erb
<%= @trail.name %>
<br>
<%= @trail.length %>
<br>
<br>
<%= link_to "Edit Trail", edit_trail_path(@trail) %>
<br>
<%= link_to "Delete Trail", @trail, method: :delete, data: { confirm: "Are you sure?" } %>

app/views/trails/welcome.html.erb
<h1>Welcome to TrailSetMC</h1>

<% if !session[:user_id] %>
  <h4>New Users - <%= link_to "Sign Up!", new_user_path %></h4>
  <h4>Exisiting Users - <%= link_to "Log In", login_path %></h4>
<% end %>

<p>TrailSetMC motorcycle app is an app designed to provide ease of mind for the solo, and/or safe rider out there. Our focus is to provide an application that assists in keeping our users safe while adventuring in the great outdoors.</p>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.label "Username:" %>
  <br>
  <%= f.text_field :username %>
  <br>
  <%= f.label "Email:" %>
  <br>
  <%= f.text_field :email %>
  <br>
  <%= f.label "First Name:" %>
  <br>
  <%= f.text_field :first_name %>
  <br>
  <%= f.label "Last Name:" %>
  <br>
  <%= f.text_field :last_name %>
  <br>
  <%= f.label "Password:" %>
  <br>
  <%= f.password_field :password %>
  <br>
  <%= f.label "Birthday:" %>
  <br>
  <%= f.date_field :birthdate %>
  <br>
  <br>
  <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<% @users.each do |user| %>
  <strong><%= user.username %></strong>
  <br>
  <%= user.first_name %> <%= user.last_name %>
  <br>
  <%= user.birthdate.strftime("%b %d, %Y") %>
  <br>
  <%= link_to user.username, user_path(user) %>
  <br>
<% end %>

app/views/users/new.html.erb
<% if !@user.errors.empty? %>
  <h3>Sorry, we experienced the following errors!</h3>
  <% @user.errors.full_messages.each do |msg| %>
    <%= msg %>
    <br>
    <br>
  <% end %>
<% end %>

<%= render 'form' %>

app/views/users/show.html.erb
<h1>Welcome 
<% if !@user.first_name.blank? %>
  <%= @user.first_name %>
<% else %>
  <%= @user.username %>
<% end %></h1>

<br>
<br>

<% if current_user %>
  <%= link_to "View Your Trails", user_trails_path(current_user) %>
<% end %>